#Lista 2: **Manejo de arreglos usando Numpy - Python**



Integrantes:

*   Aguirre Lanto Victor Manuel
*   Gasca Fragoso Pedro
*   Guevara Badillo Areli Alejandra
*   Montiel Toro Arael de Jesús
*   Ramirez Lozano Gael Martin



# Arreglo
Es una colección finita de datos del mismo tipo, que se almacenan en posiciones consecutivas de memoria y reciben un nombre común.

In [ ]:
# Importar la biblioteca NumPy
import numpy as np

In [ ]:
# Crea un arreglo de 0 dimensiones, que es básicamente un escalar.
a = np.array(13) #array de dimensión 0
print("type(a):", type(a), "\n")
print("a:", a, sep = "\n")
a

type(a): <class 'numpy.ndarray'> 

a:
13


array(13)

In [ ]:
# Crea un arreglo de 1 dimensión, similar a una lista de números.
b = np.array([1, 2, 3, 4]) #array de dimensión 1
print("b:", b, sep = "\n")
b

b:
[1 2 3 4]


array([1, 2, 3, 4])

In [ ]:
# Crea un arreglo de 2 dimensiones, similar a una matriz o tabla.
c = np.array([[1, 2, 3, 4], [5, 6, 7, 8]]) #array de deimensión 2
print("c:", c, sep = "\n")
c

c:
[[1 2 3 4]
 [5 6 7 8]]


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
# Crea un arreglo de 3 dimensiones, como un cubo de números.
d = np.array([[[1, 2, 3, 4], [5, 6, 7, 8]], [[9, 10, 11, 12], [13, 14, 15, 16]]]) #array de dimensión 3
print("d:", d, sep = "\n")
d

d:
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]


array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [ ]:
# Imprime el número de dimensiones de cada arreglo creado.
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


#Indexación básica

In [ ]:
# Muestra cómo acceder a elementos individuales o filas/capas en arreglos.
print("a =", a)
print("b[2] =", b[2])
print("c[1] =", c[1])
print("d[2] =", d[1])

a = 13
b[2] = 3
c[1] = [5 6 7 8]
d[2] = [[ 9 10 11 12]
 [13 14 15 16]]


In [ ]:
# Muestra cómo acceder a elementos específicos en arreglos multidimensionales.
print("a =", a)
print("b[2] =", b[2])
print("c[1,2] =", c[1,2])
print("d[1,0,2] =", d[1,0,2])

a = 13
b[2] = 3
c[1,2] = 7
d[1,0,2] = 11


In [ ]:
# Muestra cómo seleccionar rangos de elementos (slicing) en arreglos.
print(b[1:4]) #b = [1 2 3 4]
print(c[1,1:3]) #c = [[1 2 3 4][5 6 7 8]]
print(d[1:3,1:3,0:2])

[2 3 4]
[6 7]
[[[13 14]]]


#Diferentes tipos de datos en los arrays

In [ ]:
# Muestra el tipo de dato de los elementos dentro de un arreglo.
frutas = np.array(['Manzana', 'Naranja', 'Uva']) #cadenas
print(frutas.dtype)

<U7


In [ ]:
# Convierte un arreglo de números a un arreglo de cadenas.
number_to_string = np.array([6, 1, 2, 4, 623, 8], dtype=str) #b denota un string
print(number_to_string.dtype)
print(number_to_string)

<U3
['6' '1' '2' '4' '623' '8']


In [ ]:
# Intenta crear un arreglo con tipos de datos que no se pueden convertir (causa un error).
try:
  error_array = np.array(['a', '2', '3'], dtype=int)
except:
  print("hay un error en su lógica")

hay un error en su lógica


In [ ]:
# Convierte un arreglo de números con decimales (flotantes) a un arreglo de números enteros.
floating_array = np.array([1.1, 2.1, 3.1]) #punto flotante

int_array = floating_array.astype(int)
print(int_array)

[1 2 3]


In [ ]:
# Muestra cómo especificar diferentes tamaños para los números enteros en un arreglo.
vector = np.array([127, -127, 32767, -32767], dtype=np.int32) # entero de 1 byte = 8 bits (1 bit se necesita para almacenar el signo)
print("´vector´:\t", vector)
print("´vector.dtype´: ", vector.dtype)
vector = np.array([127, -127, 32767, -32767], dtype=np.int16) # entero de 2 bytes = 16 bits (1 bit se necesita para almacenar el signo)
print("´vector´:\t", vector)
print("´vector.dtype´: ", vector.dtype)

´vector´:	 [   127   -127  32767 -32767]
´vector.dtype´:  int32
´vector´:	 [   127   -127  32767 -32767]
´vector.dtype´:  int16


#Tamaño de los arrays

In [ ]:
# Imprime la forma (el número de elementos en cada dimensión) de cada arreglo.
print(a.shape)
print(b.shape)
print(c.shape)
print(d.shape)

()
(4,)
(2, 4)
(2, 2, 4)


#Cambio de forma de los arreglos

In [ ]:
# Cambia la forma de un arreglo 2D a un arreglo 1D.
print("c =", c, "\n") # c = [[1 2 3 4][5 6 7 8]]
c_1D = c.reshape(1, 8)
print("c_10 =", c_1D, "\n")

c = [[1 2 3 4]
 [5 6 7 8]] 

c_10 = [[1 2 3 4 5 6 7 8]] 



In [ ]:
# Cambia la forma de un arreglo 2D a otra forma 2D.
c_4D = c.reshape(4, 2)
print("c_4D =", c_4D, "\n")

c_4D = [[1 2]
 [3 4]
 [5 6]
 [7 8]] 



In [ ]:
# Imprime el arreglo d antes de cambiar su forma.
print(d)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]


In [ ]:
# Intenta cambiar la forma de un arreglo a dimensiones que no coinciden
# con el número total de elementos (causa un error).
try:
  d.reshape(3, 5)
except:
  print('Hay un error al intentar cambiar la forma del arreglo')

Hay un error al intentar cambiar la forma del arreglo


In [ ]:
# Cambia la forma de un arreglo 3D a un arreglo 4D.
d.reshape(2, 2, 2, 2)

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]]],


       [[[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]]])

In [ ]:
# Cambia la forma de un arreglo 1D a 2D,
# dejando que NumPy calcule una de las dimensiones (-1).
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr.reshape(3, -1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# Convierte un arreglo multidimensional a un arreglo 1D (aplanar).
d.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

#Transpuesta

In [ ]:
# Calcula la transpuesta de un arreglo 2D
# (intercambia filas por columnas).
print("c =", c, "\n")
print("c.T =", c.T)

c = [[1 2 3 4]
 [5 6 7 8]] 

c.T = [[1 5]
 [2 6]
 [3 7]
 [4 8]]


#Recorrer los valores de un arreglo

In [ ]:
# Itera sobre los elementos de un arreglo 1D.
for x in b:
  print(x, "\n")

1 

2 

3 

4 



In [ ]:
# Itera sobre las filas de un arreglo 2D.
for x in c:
  print(x, "\n")

[1 2 3 4] 

[5 6 7 8] 



In [ ]:
# Itera sobre las "capas" de un arreglo 3D.
for x in d:
  print(x, "\n")

[[1 2 3 4]
 [5 6 7 8]] 

[[ 9 10 11 12]
 [13 14 15 16]] 



In [ ]:
# Itera sobre todos los elementos de un arreglo 3D usando bucles anidados.
for x in d:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16


In [ ]:
# Itera eficientemente sobre todos los elementos de un arreglo usando np.nditer.
for x in np.nditer(d):
  print(x)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16


In [ ]:
# Itera sobre los elementos de un arreglo y obtiene su índice usando np.ndenumerate.
for i, x in np.ndenumerate(d):
  print('i:', i, '\t\tx:', x)

i: (0, 0, 0) 		x: 1
i: (0, 0, 1) 		x: 2
i: (0, 0, 2) 		x: 3
i: (0, 0, 3) 		x: 4
i: (0, 1, 0) 		x: 5
i: (0, 1, 1) 		x: 6
i: (0, 1, 2) 		x: 7
i: (0, 1, 3) 		x: 8
i: (1, 0, 0) 		x: 9
i: (1, 0, 1) 		x: 10
i: (1, 0, 2) 		x: 11
i: (1, 0, 3) 		x: 12
i: (1, 1, 0) 		x: 13
i: (1, 1, 1) 		x: 14
i: (1, 1, 2) 		x: 15
i: (1, 1, 3) 		x: 16


#Generación de arreglos

In [ ]:
# Genera un arreglo con valores uniformemente espaciados dentro de un rango.
print(f'np.arange(0, 1, 0.1):\n{np.arange(0, 1, 0.1)}\n')

np.arange(0, 1, 0.1):
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]



In [ ]:
# Crea un arreglo nuevo lleno de ceros con una forma específica.
print(f'np.zeros((2,3,5)):\n{np.zeros((2,3,5))}\n')

np.zeros((2,3,5)):
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]



In [ ]:
# Crea un arreglo nuevo lleno de unos con una forma específica.
print(f'np.ones((2,3,5)):\n{np.ones((2,3,5))}\n')

np.ones((2,3,5)):
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]



In [ ]:
# Crea un arreglo nuevo lleno de un valor específico con una forma determinada.
print(f'np.full((2,3,4), 1.23):\n{np.full((2,3,5), 1.23)}\n')

np.full((2,3,4), 1.23):
[[[1.23 1.23 1.23 1.23 1.23]
  [1.23 1.23 1.23 1.23 1.23]
  [1.23 1.23 1.23 1.23 1.23]]

 [[1.23 1.23 1.23 1.23 1.23]
  [1.23 1.23 1.23 1.23 1.23]
  [1.23 1.23 1.23 1.23 1.23]]]



In [ ]:
# Crea una matriz identidad (una matriz cuadrada con unos en la diagonal y ceros en el resto).
print(f'np.identity(3):\n{np.identity(3)}\n')

np.identity(3):
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]



In [ ]:
# Crea una matriz identidad (similar a np.identity).
print(f'np.eye(3):\n{np.eye(3)}\n')

np.eye(3):
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]



In [ ]:
# Crea un arreglo "vacío" con una forma específica (contiene valores arbitrarios de la memoria).
print(f'np.empty((2,3,5))"\n{np.empty((2,3,5))}\n')

np.empty((2,3,5))"
[[[1.23 1.23 1.23 1.23 1.23]
  [1.23 1.23 1.23 1.23 1.23]
  [1.23 1.23 1.23 1.23 1.23]]

 [[1.23 1.23 1.23 1.23 1.23]
  [1.23 1.23 1.23 1.23 1.23]
  [1.23 1.23 1.23 1.23 1.23]]]



#Operaciones con arrays

In [ ]:
# Encuentra los índices (posiciones) donde los elementos de un arreglo cumplen una condición.
vector = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
indx = np.where(vector%3 == 0)
print(f'type(indx):\t{type(indx)}')
print(f'indx:\t{indx}')

type(indx):	<class 'tuple'>
indx:	(array([2, 5, 8]),)


In [ ]:
# Filtra (selecciona) elementos de un arreglo usando los índices encontrados anteriormente.
filtrado = vector[indx]
print(f'filtrado:\t{filtrado}')

filtrado:	[3 6 9]


In [ ]:
# Filtra (selecciona) elementos de un arreglo usando un arreglo de valores True/False.
vector_bool = vector%3 == 0
print(f'type(vector_bool):\t{type(vector_bool)}')
print(f'vector_bool:\t\t{vector_bool}')
filtrado = vector[vector_bool]
print(f'filtrado:\t\t{filtrado}')

type(vector_bool):	<class 'numpy.ndarray'>
vector_bool:		[False False  True False False  True False False  True]
filtrado:		[3 6 9]


In [ ]:
# Calcula el seno de cada elemento en una lista usando una comprensión de lista (método estándar de Python).
import math
opt1 = [math.sin(i) for i in [1, 2, 4]]
print(opt1)

[0.8414709848078965, 0.9092974268256817, -0.7568024953079282]


In [ ]:
# Calcula el seno de cada elemento en una lista y muestra cómo formatear la salida.
import math
opt1 = [math.sin(i) for i in [1, 2, 3]]
print(f'opt1: \t{opt1}')
print(f'opt1[0]: \t{opt1[0]:.30f}')

opt1: 	[0.8414709848078965, 0.9092974268256817, 0.1411200080598672]
opt1[0]: 	0.841470984807896504875657228695


In [ ]:
# Calcula el seno de cada elemento en un arreglo NumPy de manera eficiente.
opt2 = np.sin(np.array([1, 2, 3], dtype = np.uint8), dtype = np.float64)
print(f'opt2: \t{opt2}')
print(f'opt2[0: \t{opt2[0]:.30f}')

opt2: 	[0.84147098 0.90929743 0.14112001]
opt2[0: 	0.841470984807896504875657228695


In [ ]:
# Calcula el seno solo para los elementos que cumplen una condición, guardando el resultado en otro arreglo.
x = np.array([1, 2, 3])
y = np.array([0.0, 0.0, 0.0])
np.sin(x, where = x%2 == 1, out = y)
print(f'y: \t{y}')

y: 	[0.84147098 0.         0.14112001]


In [ ]:
# Suma dos arreglos elemento a elemento usando la función np.add.
x = np.array([1, 2, 3, 4])
y = np.array([4, 5, 6, 7])
z = np.add(x, y)
print(f'z:\t{z}')

z:	[ 5  7  9 11]


In [ ]:
# Suma dos arreglos elemento a elemento usando el operador +.
z = x + y
print(f'z:\t{z}')

z:	[ 5  7  9 11]


In [ ]:
# Intenta sumar arreglos con formas diferentes (incompatibles para suma directa), lo que causa un error.
try:
  print(np.array([1, 2, 3, 4]) + np.array_split([5, 6]))
except:
  print("No se pudo hacer la operación")

No se pudo hacer la operación


In [ ]:
# Suma un número (escalar) a cada elemento de un arreglo (broadcasting).
try:
  print(np.array([1, 2, 3, 4]) + 0.9)
except:
  print("No se pudo hacer la operación")

[1.9 2.9 3.9 4.9]


In [ ]:
# Calcula el producto de todos los elementos de una matriz, o a lo largo de filas o columnas.
matriz = np.array([[3, 2, 4], [5, 2, 1], [8, 7, 6]])
print(f'matriz:\n{matriz}\n')
print(f'np.prod(matriz):\n{np.prod(matriz)}\n')
print(f'np.prod(matriz, axis=0):\n{np.prod(matriz, axis=0)}\n')
print(f'np.prod(matriz, axis=1):\n{np.prod(matriz, axis=1)}\n')

matriz:
[[3 2 4]
 [5 2 1]
 [8 7 6]]

np.prod(matriz):
80640

np.prod(matriz, axis=0):
[120  28  24]

np.prod(matriz, axis=1):
[ 24  10 336]



In [ ]:
# Calcula el producto acumulado de los elementos de una matriz (el producto de los elementos hasta la posición actual).
print(f'matriz:\n{matriz}\n')
print(f'np.cumprod(matriz):\n{np.cumprod(matriz)}\n')
print(f'np.cumprod(matriz, axis=0):\n{np.cumprod(matriz, axis=0)}\n')
print(f'np.cumprod(matriz, axis=1):\n{np.cumprod(matriz, axis=1)}\n')

matriz:
[[3 2 4]
 [5 2 1]
 [8 7 6]]

np.cumprod(matriz):
[    3     6    24   120   240   240  1920 13440 80640]

np.cumprod(matriz, axis=0):
[[  3   2   4]
 [ 15   4   4]
 [120  28  24]]

np.cumprod(matriz, axis=1):
[[  3   6  24]
 [  5  10  10]
 [  8  56 336]]



In [ ]:
# Calcula la media (promedio) y la desviación estándar de los elementos de una matriz.
print(f'media: {np.mean(matriz)}')
print(f'deviación estándar muestral: {np.std(matriz, ddof=1)}')

media: 4.222222222222222
deviación estándar muestral: 2.438123139721299


#Multiplicación Matricial

In [ ]:
# Define dos arreglos que se usarán para la multiplicación matricial.
arr1 = np.array([[1,2,3], [4,5,6]]) #tamaño 2,3
arr2 = np.array([[6,5,4], [3,2,1]]) #tamaño 2,3

In [ ]:
# Realiza la multiplicación matricial de dos arreglos usando el operador @.
print(arr1 @ arr2.T) #2,3 y 3,2 = 2,2

[[28 10]
 [73 28]]


In [ ]:
# Realiza la multiplicación matricial de dos arreglos usando la función np.matmul.
print(np.matmul(arr1,arr2.T))

[[28 10]
 [73 28]]


In [ ]:
# Realiza la multiplicación matricial de dos arreglos usando la función np.dot.
print(np.dot(arr1,arr2.T))

[[28 10]
 [73 28]]


In [ ]:
# Intenta realizar una multiplicación matricial con tipos de datos incompatibles (causa un error).
try:
  print(0.9 @ arr1) #float y arreglo de tasmaño 2,3
except:
  print("No se pudo hacer la operación")

No se pudo hacer la operación


In [ ]:
# Intenta realizar una multiplicación matricial con formas de arreglos incompatibles (causa un error).
try:
  print(np.array([0.9]) @ arr1) #tamaño 1 y tamaño 2,3
except:
  print("No se pudo hacer la operación")

No se pudo hacer la operación


In [ ]:
# Realiza la multiplicación matricial de un vector fila por una matriz.
try:
  print(np.array([200, 100]) @ arr1) #tamaño 2 y tamaño 2,3
except:
  print("No se pudo hacer la operación")

[ 600  900 1200]


In [ ]:
# Realiza la multiplicación matricial de una matriz por un vector columna.
try:
  print(np.matmul(arr1, np.array([10, 20, 30]))) #2,3 y 3
except:
  print("No se pudo hacer la operación")

[140 320]
